cursor #e9e2d4
cursor_text_color #cec6b4

foreground            #e9e2d4
background            #16130b
selection_foreground  #373016
selection_background  #d2c6a1
url_color             #dec56e

# black
color8   #e9e2d4
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #e9e2d4
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #dec56e
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #e9e2d4
color14  #d2c6a1

# white
color15   #e7e7e7
color7  #f0f0f0
