[mgr]
cwd = { fg = "blue", bold = true }
border_style = { fg = "darkgray" }

[indicator]
parent = { reversed = true }
current = { reversed = true, bold = true }
preview = { underline = true }
padding = { open = "", close = "" }

[tabs]
active = { fg = "black", bg = "blue", bold = true }
inactive = { fg = "gray", bg = "reset" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "black", bg = "blue", bold = true }
normal_alt = { fg = "blue", bg = "reset" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[filetype]
rules = [
  { mime = "**/image/*", fg = "yellow" },
  { mime = "**/{audio,video}/*", fg = "magenta" },
  { url = "*/", fg = "blue", bold = true },
  { url = "*", fg = "white" },
]
