# Preload Wallpapers
preload = /home/siverteh/.config/ml4w/wallpapers/autumns.hues.png

# Set Wallpapers
wallpaper {
    monitor = eDP-1
    path = /home/siverteh/.config/ml4w/wallpapers/autumns.hues.png
    fit_mode = cover
}

# Disable Splash
splash = false
ipc = true
