-- One owner per desktop function. UWSM handles the graphical session and XDG autostart.
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/pam_kwallet_init")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("systemctl --user start siverteh-os-shell.service")
    hl.exec_cmd("~/.config/hypr/scripts/low-battery.sh")
    hl.exec_cmd("~/.config/hypr/scripts/coding-setup.sh")
end)
