-- Generated by Siverteh OS
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2880x1800@120",
    position = "0x0",
    scale = 1.5,
})

-- Samsung Odyssey G85SB connected over USB-C / DisplayPort.
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "3440x1440@119.96Hz",
    position = "1920x0",
    scale = 1,
})
