import fs from 'node:fs';
const target=await (await fetch('http://127.0.0.1:17944/json/new?about:blank',{method:'PUT'})).json();
const socket=new WebSocket(target.webSocketDebuggerUrl);
await new Promise(r=>socket.addEventListener('open',r,{once:true}));
let seq=0;const pending=new Map(),errors=[];
socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(m.error);else p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);});
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception.description);return r.result.value;}
await call('Runtime.enable');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:950,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:'http://127.0.0.1:17843'});
for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,150));if(await evaluate('document.getElementById("loading")?.hidden'))break;}
const initial=await evaluate('({hubs:document.querySelectorAll(".hub-link").length,notes:graph.noteCount,hits:hits.length})');
if(initial.hubs<4||initial.notes<1||initial.hits<4)throw Error('Graph failed to render: '+JSON.stringify(initial));
fs.mkdirSync(process.env.HOME+'/.local/state/siverteh-observatory/qa',{recursive:true});
const out=process.env.HOME+'/.local/state/siverteh-observatory/qa';
const snap=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(out+'/brain-overview.png',Buffer.from(snap.data,'base64'));
await evaluate('document.querySelector(".hub-link").click()');
await new Promise(r=>setTimeout(r,750));
const expandedState=await evaluate('({expanded:[...expanded],hits:hits.length,heading:document.querySelector("#inspector h2").textContent})');
if(!expandedState.expanded.includes('newbringer')||expandedState.hits<=initial.hits)throw Error('Hub expansion failed');
const hubCamera=await evaluate('({zoom,center:project(positions().get("newbringer")),width:W,height:H})');
if(hubCamera.zoom<=1.2||Math.hypot(hubCamera.center.x-hubCamera.width*.5,hubCamera.center.y-hubCamera.height*.56)>10)throw Error('Hub camera did not focus');
await evaluate('select(byId.get("newbringer:camera"))');
await new Promise(r=>setTimeout(r,750));
const topicCamera=await evaluate('({zoom,center:project(positions().get("newbringer:camera")),width:W,height:H})');
if(topicCamera.zoom<=hubCamera.zoom||Math.hypot(topicCamera.center.x-topicCamera.width*.5,topicCamera.center.y-topicCamera.height*.56)>10)throw Error('Topic camera did not travel closer');
const snap2=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(out+'/brain-expanded.png',Buffer.from(snap2.data,'base64'));
if(!(await evaluate('labelBoxes.filter(x=>x.n.kind==="note").length>=10&&document.querySelector(".detail-kind").textContent.startsWith("Planet")')))throw Error('Moon labels or celestial hierarchy missing');
const moonLabel=await evaluate('(()=>{const h=hits.find(h=>h.box&&h.n.kind==="note"),b=canvas.getBoundingClientRect();return {id:h.n.id,x:b.left+h.x,y:b.top+h.y};})()');
await call('Input.dispatchMouseEvent',{type:'mousePressed',x:moonLabel.x,y:moonLabel.y,button:'left',clickCount:1});
await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:moonLabel.x,y:moonLabel.y,button:'left',clickCount:1});
if(!(await evaluate('selected.id==='+JSON.stringify(moonLabel.id))))throw Error('Named moon label was not clickable');
await evaluate('document.getElementById("back").click()');
await new Promise(r=>setTimeout(r,750));
await evaluate('document.getElementById("zoom-out").click()');
await new Promise(r=>setTimeout(r,750));
if(!(await evaluate('zoom<2.4')))throw Error('Visible zoom-out control failed');
await evaluate('document.getElementById("back").click()');
await new Promise(r=>setTimeout(r,750));
if(!(await evaluate('selected.id==="newbringer"&&!expanded.has("newbringer:camera")')))throw Error('Back did not return to the parent star');
await evaluate('document.getElementById("back").click()');
await new Promise(r=>setTimeout(r,750));
if(!(await evaluate('selected===null&&document.getElementById("back").disabled')))throw Error('Back did not return to the overview');
await evaluate('select(byId.get("newbringer"));select(byId.get("newbringer:camera"))');
await evaluate('select(children(byId.get("newbringer:camera")).filter(n=>n.kind==="note").at(-1))');
await new Promise(r=>setTimeout(r,750));
if(!(await evaluate('positions().has(selected.id)&&Math.hypot(project(positions().get(selected.id)).x-W*.5,project(positions().get(selected.id)).y-H*.56)<10')))throw Error('Evidence outside the default visible subset did not focus');
await evaluate('document.getElementById("library").click();document.getElementById("search").value="zzzz-no-results";document.getElementById("search").dispatchEvent(new Event("input"))');
if(await evaluate('document.querySelectorAll(".search-result").length')!==0)throw Error('Search failed');
await evaluate('select(graph.nodes.find(n=>n.kind==="note"))');
await new Promise(r=>setTimeout(r,300));
if(!(await evaluate('document.querySelector(".note-body").textContent.length>20')))throw Error('Note reader failed');
await call('Emulation.setDeviceMetricsOverride',{width:900,height:700,deviceScaleFactor:1,mobile:false});
await evaluate('setTab("universe")');
await new Promise(r=>setTimeout(r,300));
if(await evaluate('document.documentElement.scrollWidth>innerWidth'))throw Error('Layout overflows');
await evaluate('document.getElementById("home").click()');
await new Promise(r=>setTimeout(r,750));
if(!(await evaluate('Math.abs(zoom-1)<.05&&Math.hypot(camera.x,camera.y,camera.z)<3&&selected===null')))throw Error('Overview did not restore camera');
const expansionCheck=await evaluate('(()=>{for(let i=0;i<4;i++)(()=>{const n={id:"qa-extra-"+i,label:"QA world "+i,kind:"hub",count:0,radius:20,color:"#a9c9f2"};graph.nodes.push(n);byId.set(n.id,n);})();renderNav();const a=positions(),ids=graph.nodes.filter(n=>n.id.startsWith("qa-extra-")).map(n=>n.id);fitOverview();const distinct=ids.every((id,i)=>ids.slice(i+1).every(other=>Math.hypot(a.get(id).x-a.get(other).x,a.get(id).y-a.get(other).y)>150));const original=a.get(ids[0]);graph.nodes.reverse();const b=positions();return {distinct,stable:original.x===b.get(ids[0]).x&&original.y===b.get(ids[0]).y,zoom:cameraTarget.zoom};})()');
if(!expansionCheck.distinct||!expansionCheck.stable||expansionCheck.zoom>=1)throw Error('Additional worlds overlap or fail to fit');
await new Promise(r=>setTimeout(r,150));
if(errors.length)throw Error([...new Set(errors)].join('\n'));
console.log(JSON.stringify({initial,expanded:expandedState,hubZoom:hubCamera.zoom,topicZoom:topicCamera.zoom,cameraFocus:'passed',back:'passed',zoomOut:'passed',moonLabels:'passed',overview:'passed',browserErrors:errors.length,search:'passed',noteReader:'passed',responsive:'passed',screenshots:out}));
socket.close();
