#!/usr/bin/env python3
"""Launch native Dolphin with Nacre's existing palette and archive navigation."""

import configparser
import datetime as dt
import fcntl
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

HOME = Path.home()


def config(path):
    result = configparser.ConfigParser(interpolation=None, strict=False)
    result.optionxform = str
    if path.exists():
        result.read(path)
    return result


def save(path, values):
    stream = io.StringIO()
    values.write(stream, space_around_delimiters=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, pending = tempfile.mkstemp(dir=path.parent)
    with os.fdopen(fd, "w") as output:
        output.write(stream.getvalue())
    os.chmod(pending, 0o600)
    os.replace(pending, path)


def setup(home=None):
    home = Path.home() if home is None else Path(home)
    state = home / ".local/state/nacre"
    state.mkdir(parents=True, exist_ok=True, mode=0o700)
    with (state / "dolphin-setup.lock").open("a") as guard:
        fcntl.flock(guard, fcntl.LOCK_EX)
        marker = state / "dolphin-default.json"
        if marker.exists():
            return
        backup = (
            state
            / "backups"
            / (
                "dolphin-"
                + dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
            )
        )
        backup.mkdir(parents=True, mode=0o700)
        paths = ["dolphinrc", "mimeapps.list"]
        for name in paths:
            path = home / ".config" / name
            if path.is_file():
                dest = backup / name
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, dest)
        dolphin = config(home / ".config/dolphinrc")
        defaults = {
            "General": {
                "BrowseThroughArchives": "true",
                "GlobalViewProps": "true",
                "OpenExternallyCalledFolderInNewTab": "true",
                "EditableUrl": "false",
                "ShowStatusBar": "FullWidth",
            },
            "IconsMode": {
                "IconSize": "80",
                "PreviewSize": "96",
                "MaximumTextLines": "2",
                "UseSystemFont": "true",
            },
            "KFileDialog Settings": {
                "Places Icons Auto-resize": "false",
                "Places Icons Static Size": "22",
            },
            "MainWindow": {"MenuBar": "Disabled"},
            # Nacre is regenerated by the existing palette owner.
            "UiSettings": {"ColorScheme": "Nacre"},
        }
        for section, values in defaults.items():
            if not dolphin.has_section(section):
                dolphin.add_section(section)
            for key, value in values.items():
                dolphin[section][key] = value
        save(home / ".config/dolphinrc", dolphin)
        mime = config(home / ".config/mimeapps.list")
        if not mime.has_section("Default Applications"):
            mime.add_section("Default Applications")
        for kind in [
            "inode/directory",
            "application/zip",
            "application/x-zip-compressed",
        ]:
            mime["Default Applications"][kind] = "org.kde.dolphin.desktop"
        save(home / ".config/mimeapps.list", mime)
        marker.write_text(
            json.dumps({"backup": str(backup), "defaults": defaults}, indent=2) + "\n"
        )
        marker.chmod(0o600)


def environment():
    env = os.environ.copy()
    for name in [
        "LD_LIBRARY_PATH",
        "QT_PLUGIN_PATH",
        "QML_IMPORT_PATH",
        "QML2_IMPORT_PATH",
        "GTK_MODULES",
        "NACRE_THUNAR_STYLE",
    ]:
        env.pop(name, None)
    env["QT_QPA_PLATFORMTHEME"] = "xdgdesktopportal"
    env["QT_STYLE_OVERRIDE"] = "NacreDolphin"
    # This directory contains only Nacre's uniquely named public-Qt style plugin.
    env["QT_PLUGIN_PATH"] = str(HOME / ".local/share/nacre/dolphin-style")
    env["XDG_MENU_PREFIX"] = "arch-"
    return env


def main():
    setup()
    if "--setup" in sys.argv:
        return
    env = environment()
    os.execve("/usr/bin/dolphin", ["dolphin", *(sys.argv[1:] or [str(HOME)])], env)


if __name__ == "__main__":
    main()
